<?xml version="1.0" encoding="utf-8"?>
<Project>
  <!-- v141_xp otherwise changes true whole-program optimization to /LTCG:incremental. -->
  <ItemDefinitionGroup Condition="'$(Configuration)' == 'Release'">
    <Link>
      <LinkTimeCodeGeneration>UseLinkTimeCodeGeneration</LinkTimeCodeGeneration>
    </Link>
  </ItemDefinitionGroup>
</Project>
